In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
cd /content/drive/"MyDrive/Colab Notebooks"

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import glob
import cv2

In [ ]:
from keras.models import Model, Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.layers import BatchNormalization
import os
import seaborn as sns

In [ ]:
print(os.listdir("/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images"))

In [ ]:
 Size = 200

In [ ]:
train_images =[]
train_labels =[]
for directory_path in glob.glob("/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/train/images/*"):
  label = directory_path.split("\\")[-1]
  print(label)
  for img_path in glob.glob(os.path.join(directory_path,"*.jpg")):
    print(img_path)
    img= cv2.imread(img_path,cv2.IMREAD_COLOR)
    img = cv2.resize(img,(Size,Size))
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    img = img.reshape(-1)
    train_images.append(img)
    train_labels.append(label)

/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/train/images/pitted_surface
/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/train/images/pitted_surface/pitted_surface_174.jpg
/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/train/images/pitted_surface/pitted_surface_62.jpg
/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/train/images/pitted_surface/pitted_surface_71.jpg
/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/train/images/pitted_surface/pitted_surface_195.jpg
/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/train/images/pitted_surface/pitted_surface_222 (1).jpg
/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/train/images/pitted_surface/pitted_surface_120.jpg
/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/train/images/pitted_surface/pitted_surface_103.jpg
/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/train/images/pitted_surface/pitted_surface_210.jpg
/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/train/images

In [ ]:
train_images= np.array(train_images)
train_labels= np.array(train_labels)

In [ ]:
test_images =[]
test_labels =[]
for directory_path in glob.glob("/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/test/images/*"):
  label = directory_path.split("\\")[-1]
  print(label)
  for img_path in glob.glob(os.path.join(directory_path,"*.jpg")):
    print(img_path)
    img= cv2.imread(img_path,cv2.IMREAD_COLOR)
    img = cv2.resize(img,(Size,Size))
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    img = img.reshape(-1)
    test_images.append(img)
    test_labels.append(label)

test_images= np.array(test_images)
test_labels= np.array(test_labels)

/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/test/images/pitted_surface
/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/test/images/pitted_surface/pitted_surface_11.jpg
/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/test/images/pitted_surface/pitted_surface_25.jpg
/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/test/images/pitted_surface/pitted_surface_54.jpg
/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/test/images/pitted_surface/pitted_surface_52.jpg
/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/test/images/pitted_surface/pitted_surface_13.jpg
/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/test/images/pitted_surface/pitted_surface_21.jpg
/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/test/images/pitted_surface/pitted_surface_8.jpg
/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/test/images/pitted_surface/pitted_surface_46.jpg
/content/drive/MyDrive/Colab Notebooks/NEU-DET/ images/test/images/pitted_surface/pitte

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(test_labels)
test_labels_encoded = le.transform(test_labels)
le.fit(train_labels)
train_labels_encoded = le.transform(train_labels)

In [ ]:
x_train, y_train, x_test, y_test = train_images, train_labels_encoded, test_images, test_labels_encoded

In [ ]:
from sklearn import svm

svc = svm.SVC(kernel='linear', C=1).fit(x_train, y_train)




In [ ]:
rbf_svc = svm.SVC(kernel='rbf', gamma=0.5, C=1).fit(x_train, y_train)

In [ ]:
poly_svc = svm.SVC(kernel='poly', degree=5, C=1).fit(x_train, y_train)

In [ ]:
y_pred = svc.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test,y_pred))

[[ 8 19  1 22  8  2]
 [ 0 50  0  3  3  4]
 [ 7  8 30  8  5  2]
 [ 0 18  1 32  7  2]
 [ 2 23  2  7 22  4]
 [ 3 38  1  6  3 11]]
              precision    recall  f1-score   support

           0       0.40      0.13      0.20        60
           1       0.32      0.83      0.46        60
           2       0.86      0.50      0.63        60
           3       0.41      0.53      0.46        60
           4       0.46      0.37      0.41        60
           5       0.44      0.18      0.25        62

    accuracy                           0.42       362
   macro avg       0.48      0.42      0.40       362
weighted avg       0.48      0.42      0.40       362

0.42265193370165743


In [ ]:
y_pred = rbf_svc.predict(x_test)

In [ ]:
 
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test,y_pred))

[[ 0  0  0  0  0 60]
 [ 0  0  0  0  0 60]
 [ 0  0  0  0  0 60]
 [ 0  0  0  0  0 60]
 [ 0  0  0  0  0 60]
 [ 0  0  0  0  0 62]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        60
           1       0.00      0.00      0.00        60
           2       0.00      0.00      0.00        60
           3       0.00      0.00      0.00        60
           4       0.00      0.00      0.00        60
           5       0.17      1.00      0.29        62

    accuracy                           0.17       362
   macro avg       0.03      0.17      0.05       362
weighted avg       0.03      0.17      0.05       362

0.1712707182320442


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
y_pred = poly_svc.predict(x_test)

In [ ]:
 

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test,y_pred))

[[24 17  1 12  5  1]
 [ 0 44  0  0  3 13]
 [27  5 17  3  6  2]
 [20 14  0 22  4  0]
 [22 14  0  1 22  1]
 [ 6 32  0  6  2 16]]
              precision    recall  f1-score   support

           0       0.24      0.40      0.30        60
           1       0.35      0.73      0.47        60
           2       0.94      0.28      0.44        60
           3       0.50      0.37      0.42        60
           4       0.52      0.37      0.43        60
           5       0.48      0.26      0.34        62

    accuracy                           0.40       362
   macro avg       0.51      0.40      0.40       362
weighted avg       0.51      0.40      0.40       362

0.4005524861878453
